### ISSUE TITLE
chat failing to build

### ISSUE THREAD

**Issue by jbpratt** [MemeLabs/chat-gui#378]
On fresh clone, chat is failing to build

```
projects >git clone git@github.com:memelabs/chat-gui
Cloning into 'chat-gui'...
remote: Enumerating objects: 289, done.
remote: Counting objects: 100% (289/289), done.
remote: Compressing objects: 100% (235/235), done.
remote: Total 4522 (delta 135), reused 193 (delta 54), pack-reused 4233
Receiving objects: 100% (4522/4522), 27.02 MiB | 21.04 MiB/s, done.
Resolving deltas: 100% (2391/2391), done.
projects >cd chat-gui/
chat-gui >npm ci

> fsevents@1.2.7 install /home/jbpratt/projects/chat-gui/node_modules/fsevents
> node install


> node-sass@4.14.1 install /home/jbpratt/projects/chat-gui/node_modules/node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v4.14.1/linux-x64-88_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v4.14.1/linux-x64-88_binding.node":

HTTP error 404 Not Found

Hint: If github.com is not accessible in your location
      try setting a proxy via HTTP_PROXY, e.g.

      export HTTP_PROXY=http://example.com:1234

or configure npm proxy via

      npm config set proxy http://example.com:8080

> node-sass@4.14.1 postinstall /home/jbpratt/projects/chat-gui/node_modules/node-sass
> node scripts/build.js
...
[7] multi (webpack)-dev-server/client?http://localhost:8282 ./assets/chat/css/emotes.scss 40 bytes {emotes} [built]
[8] multi (webpack)-dev-server/client?http://localhost:8282 ./assets/notification-request/style.scss ./assets/notification-request/persona.png ./assets/notification-request/settings-guide.png ./assets/notification-request/script.js 76 bytes {notification-request} [built]
[9] multi (webpack)-dev-server/client?http://localhost:8282 core-js/es6 jquery normalize.css font-awesome/scss/font-awesome.scss ./assets/chat/css/style.scss ./assets/dev/dev-chat/dev-chat.js 100 bytes {dev-chat} [built]
[./assets/chat.js] 624 bytes {chat} [built]
[./assets/chat/css/emotes.scss] 1.06 KiB {emotes} [built] [failed] [1 error]
[./assets/chat/css/onstream.scss] 39 bytes {chatstreamed} [built]
[./assets/chat/css/style.scss] 1.05 KiB {chat} {chatstreamed} {dev-chat} [built] [failed] [1 error]
[./assets/chat/js/notification.js] 5.2 KiB {chat} {chatstreamed} [built]
[./assets/dev/dev-chat/dev-chat.js] 924 bytes {dev-chat} [built]
[./assets/notification-request/persona.png] 68 bytes {notification-request} [built]
[./assets/notification-request/script.js] 3.84 KiB {notification-request} [built]
[./assets/notification-request/settings-guide.png] 75 bytes {notification-request} [built]
[./assets/notification-request/style.scss] 39 bytes {notification-request} [built]
    + 562 hidden modules

ERROR in ./assets/chat/css/emotes.scss
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):

@import "../../emotes/emoticons";
^
      File to import not found or unreadable: ../../emotes/emoticons.
      in /home/jbpratt/projects/chat-gui/assets/chat/css/emotes.scss (line 1, column 1)
    at /home/jbpratt/projects/chat-gui/node_modules/webpack/lib/NormalModule.js:301:20
    at /home/jbpratt/projects/chat-gui/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /home/jbpratt/projects/chat-gui/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at context.callback (/home/jbpratt/projects/chat-gui/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at Object.callback (/home/jbpratt/projects/chat-gui/node_modules/sass-loader/dist/index.js:89:7)
    at Object.done [as callback] (/home/jbpratt/projects/chat-gui/node_modules/neo-async/async.js:8077:18)
    at options.error (/home/jbpratt/projects/chat-gui/node_modules/node-sass/lib/index.js:294:32)
 @ multi ./assets/chat/css/emotes.scss emotes[0]

ERROR in ./assets/chat/css/style.scss
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):

@import "../../icons/icons";
^
      File to import not found or unreadable: ../../icons/icons.
      in /home/jbpratt/projects/chat-gui/assets/chat/css/style.scss (line 2, column 1)
    at /home/jbpratt/projects/chat-gui/node_modules/webpack/lib/NormalModule.js:301:20
    at /home/jbpratt/projects/chat-gui/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /home/jbpratt/projects/chat-gui/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at context.callback (/home/jbpratt/projects/chat-gui/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at Object.callback (/home/jbpratt/projects/chat-gui/node_modules/sass-loader/dist/index.js:89:7)
    at Object.done [as callback] (/home/jbpratt/projects/chat-gui/node_modules/neo-async/async.js:8077:18)
    at options.error (/home/jbpratt/projects/chat-gui/node_modules/node-sass/lib/index.js:294:32)
 @ multi core-js/es6 jquery normalize.css font-awesome/scss/font-awesome.scss ./assets/chat/js/notification ./assets/chat/css/style.scss ./assets/chat.js ./assets/sounds/notification.wav chat[5]

ERROR in ./assets/chat/js/formatters.js
Module not found: Error: Can't resolve '../../tld.json' in '/home/jbpratt/projects/chat-gui/assets/chat/js'
 @ ./assets/chat/js/formatters.js 5:11-36
 @ ./assets/chat/js/messages.js
 @ ./assets/chat/js/chat.js
 @ ./assets/chat.js
 @ multi core-js/es6 jquery normalize.css font-awesome/scss/font-awesome.scss ./assets/chat/js/notification ./assets/chat/css/style.scss ./assets/chat.js ./assets/sounds/notification.wav
Child html-webpack-plugin for "chatstreamed.html":
     1 asset
    Entrypoint undefined = chatstreamed.html
    [./node_modules/html-webpack-plugin/lib/loader.js!./assets/chatstreamed.html] 476 bytes {0} [built]
Child html-webpack-plugin for "dev/dev-chat.html":
     1 asset
    Entrypoint undefined = dev/dev-chat.html
    [./node_modules/html-webpack-plugin/lib/loader.js!./assets/index.html] 18.2 KiB {0} [built]
Child html-webpack-plugin for "index.html":
     1 asset
    Entrypoint undefined = index.html
    [./node_modules/html-webpack-plugin/lib/loader.js!./assets/index.html] 18.2 KiB {0} [built]
Child html-webpack-plugin for "notification-request.html":
     3 assets
    Entrypoint undefined = notification-request.html
    [./assets/notification-request/persona.png] 68 bytes {0} [built]
    [./assets/notification-request/settings-guide.png] 75 bytes {0} [built]
    [./node_modules/html-webpack-plugin/lib/loader.js!./assets/notification-request/notification-request.html] 1.24 KiB {0} [built]
Child mini-css-extract-plugin node_modules/css-loader/index.js!node_modules/postcss-loader/lib/index.js!node_modules/sass-loader/dist/cjs.js!assets/chat/css/emotes.scss:
    Entrypoint mini-css-extract-plugin = *
    [./node_modules/css-loader/index.js!./node_modules/postcss-loader/lib/index.js!./node_modules/sass-loader/dist/cjs.js!./assets/chat/css/emotes.scss] ./node_modules/css-loader!./node_modules/postcss-loader/lib!./node_modules/sass-loader/dist/cjs.js!./assets/chat/css/emotes.scss 288 bytes {mini-css-extract-plugin} [built] [failed] [1 error]

    ERROR in ./assets/chat/css/emotes.scss (./node_modules/css-loader!./node_modules/postcss-loader/lib!./node_modules/sass-loader/dist/cjs.js!./assets/chat/css/emotes.scss)
    Module build failed (from ./node_modules/sass-loader/dist/cjs.js):

    @import "../../emotes/emoticons";
    ^
          File to import not found or unreadable: ../../emotes/emoticons.
          in /home/jbpratt/projects/chat-gui/assets/chat/css/emotes.scss (line 1, column 1)
Child mini-css-extract-plugin node_modules/css-loader/index.js!node_modules/postcss-loader/lib/index.js!node_modules/sass-loader/dist/cjs.js!assets/chat/css/onstream.scss:
    Entrypoint mini-css-extract-plugin = *
    [./node_modules/css-loader/index.js!./node_modules/postcss-loader/lib/index.js!./node_modules/sass-loader/dist/cjs.js!./assets/chat/css/onstream.scss] ./node_modules/css-loader!./node_modules/postcss-loader/lib!./node_modules/sass-loader/dist/cjs.js!./assets/chat/css/onstream.scss 1.6 KiB {mini-css-extract-plugin} [built]
    [./node_modules/css-loader/index.js!./node_modules/roboto-fontface/css/roboto/roboto-fontface.css] ./node_modules/css-loader!./node_modules/roboto-fontface/css/roboto/roboto-fontface.css 6.39 KiB {mini-css-extract-plugin} [built]
    [./node_modules/css-loader/lib/css-base.js] 2.21 KiB {mini-css-extract-plugin} [built]
    [./node_modules/css-loader/lib/url/escape.js] 448 bytes {mini-css-extract-plugin} [built]
    [./node_modules/roboto-fontface/fonts/roboto/Roboto-Black.woff] 76 bytes {mini-css-extract-plugin} [built]
    [./node_modules/roboto-fontface/fonts/roboto/Roboto-Black.woff2] 77 bytes {mini-css-extract-plugin} [built]
    [./node_modules/roboto-fontface/fonts/roboto/Roboto-BlackItalic.woff] 82 bytes {mini-css-extract-plugin} [built]
    [./node_modules/roboto-fontface/fonts/roboto/Roboto-BlackItalic.woff2] 83 bytes {mini-css-extract-plugin} [built]
    [./node_modules/roboto-fontface/fonts/roboto/Roboto-Bold.woff] 75 bytes {mini-css-extract-plugin} [built]
    [./node_modules/roboto-fontface/fonts/roboto/Roboto-Bold.woff2] 76 bytes {mini-css-extract-plugin} [built]
    [./node_modules/roboto-fontface/fonts/roboto/Roboto-BoldItalic.woff] 81 bytes {mini-css-extract-plugin} [built]
    [./node_modules/roboto-fontface/fonts/roboto/Roboto-BoldItalic.woff2] 82 bytes {mini-css-extract-plugin} [built]
    [./node_modules/roboto-fontface/fonts/roboto/Roboto-Light.woff] 76 bytes {mini-css-extract-plugin} [built]
    [./node_modules/roboto-fontface/fonts/roboto/Roboto-Light.woff2] 77 bytes {mini-css-extract-plugin} [built]
    [./node_modules/roboto-fontface/fonts/roboto/Roboto-LightItalic.woff] 82 bytes {mini-css-extract-plugin} [built]
        + 13 hidden modules
Child mini-css-extract-plugin node_modules/css-loader/index.js!node_modules/postcss-loader/lib/index.js!node_modules/sass-loader/dist/cjs.js!assets/chat/css/style.scss:
    Entrypoint mini-css-extract-plugin = *
    [./node_modules/css-loader/index.js!./node_modules/postcss-loader/lib/index.js!./node_modules/sass-loader/dist/cjs.js!./assets/chat/css/style.scss] ./node_modules/css-loader!./node_modules/postcss-loader/lib!./node_modules/sass-loader/dist/cjs.js!./assets/chat/css/style.scss 277 bytes {mini-css-extract-plugin} [built] [failed] [1 error]

    ERROR in ./assets/chat/css/style.scss (./node_modules/css-loader!./node_modules/postcss-loader/lib!./node_modules/sass-loader/dist/cjs.js!./assets/chat/css/style.scss)
    Module build failed (from ./node_modules/sass-loader/dist/cjs.js):

    @import "../../icons/icons";
    ^
          File to import not found or unreadable: ../../icons/icons.
          in /home/jbpratt/projects/chat-gui/assets/chat/css/style.scss (line 2, column 1)
Child mini-css-extract-plugin node_modules/css-loader/index.js!node_modules/postcss-loader/lib/index.js!node_modules/sass-loader/dist/cjs.js!assets/notification-request/style.scss:
    Entrypoint mini-css-extract-plugin = *
    [./node_modules/css-loader/index.js!./node_modules/postcss-loader/lib/index.js!./node_modules/sass-loader/dist/cjs.js!./assets/notification-request/style.scss] ./node_modules/css-loader!./node_modules/postcss-loader/lib!./node_modules/sass-loader/dist/cjs.js!./assets/notification-request/style.scss 1.74 KiB {mini-css-extract-plugin} [built]
    [./node_modules/css-loader/lib/css-base.js] 2.21 KiB {mini-css-extract-plugin} [built]
Child mini-css-extract-plugin node_modules/css-loader/index.js!node_modules/postcss-loader/lib/index.js!node_modules/sass-loader/dist/cjs.js!node_modules/font-awesome/scss/font-awesome.scss:
    Entrypoint mini-css-extract-plugin = *
    [./node_modules/css-loader/index.js!./node_modules/postcss-loader/lib/index.js!./node_modules/sass-loader/dist/cjs.js!./node_modules/font-awesome/scss/font-awesome.scss] ./node_modules/css-loader!./node_modules/postcss-loader/lib!./node_modules/sass-loader/dist/cjs.js!./node_modules/font-awesome/scss/font-awesome.scss 32.2 KiB {mini-css-extract-plugin} [built]
    [./node_modules/css-loader/lib/css-base.js] 2.21 KiB {mini-css-extract-plugin} [built]
    [./node_modules/css-loader/lib/url/escape.js] 448 bytes {mini-css-extract-plugin} [built]
    [./node_modules/font-awesome/fonts/fontawesome-webfont.eot] 82 bytes {mini-css-extract-plugin} [built]
    [./node_modules/font-awesome/fonts/fontawesome-webfont.eot?v=4.7.0] 82 bytes {mini-css-extract-plugin} [built]
    [./node_modules/font-awesome/fonts/fontawesome-webfont.svg?v=4.7.0] 82 bytes {mini-css-extract-plugin} [built]
    [./node_modules/font-awesome/fonts/fontawesome-webfont.ttf?v=4.7.0] 82 bytes {mini-css-extract-plugin} [built]
    [./node_modules/font-awesome/fonts/fontawesome-webfont.woff2?v=4.7.0] 84 bytes {mini-css-extract-plugin} [built]
    [./node_modules/font-awesome/fonts/fontawesome-webfont.woff?v=4.7.0] 83 bytes {mini-css-extract-plugin} [built]
Child mini-css-extract-plugin node_modules/css-loader/index.js!node_modules/postcss-loader/lib/index.js!node_modules/sass-loader/dist/cjs.js!node_modules/normalize.css/normalize.css:
    Entrypoint mini-css-extract-plugin = *
    [./node_modules/css-loader/index.js!./node_modules/postcss-loader/lib/index.js!./node_modules/sass-loader/dist/cjs.js!./node_modules/normalize.css/normalize.css] ./node_modules/css-loader!./node_modules/postcss-loader/lib!./node_modules/sass-loader/dist/cjs.js!./node_modules/normalize.css/normalize.css 2.02 KiB {mini-css-extract-plugin} [built]
    [./node_modules/css-loader/lib/css-base.js] 2.21 KiB {mini-css-extract-plugin} [built]
ℹ ｢wdm｣: Failed to compile.
```

**Comment by jbpratt** [comment]
`npm run build` should be ran first. There is probably improvements to this process that can happen.
